[0m22:35:23.780122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e21449340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e21054350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e21bbed80>]}


============================== 22:35:23.802690 | 75ab4604-3a61-4579-9762-ee7e4c99e4d6 ==============================
[0m22:35:23.802690 [info ] [MainThread]: Running with dbt=1.9.0
[0m22:35:23.804446 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/mgr_phil/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:35:23.878070 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/mgr_phil/.dbt')}
[0m22:35:23.879673 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:35:48.089057 [debug] [MainThread]: Starter project path: /home/mgr_phil/Documents/docker-dbt-airflow/data-engineering-app/dbt-env/lib/python3.12/site-packages/dbt/include/starter_project
[0m22:35:48.120632 [info ] [MainThread]: 
Your new dbt project "ecommerce_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:35:48.129915 [info ] [MainThread]: Setting up your profile.
[0m22:39:31.876849 [info ] [MainThread]: Profile ecommerce_dbt written to /home/mgr_phil/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:39:31.889199 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 248.33286, "process_in_blocks": "4736", "process_kernel_time": 0.311705, "process_mem_max_rss": "93292", "process_out_blocks": "88", "process_user_time": 2.91125}
[0m22:39:31.893104 [debug] [MainThread]: Command `dbt init` succeeded at 22:39:31.890777 after 248.34 seconds
[0m22:39:31.895324 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e213ee420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e20f7f050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b1e215b8200>]}
[0m22:39:31.897263 [debug] [MainThread]: Flushing usage events
[0m22:39:32.875323 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:14:45.708880 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f977fb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f7581240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f7581300>]}


============================== 23:14:45.746196 | de052835-a66a-43b7-9281-ab1ea0e8a8d4 ==============================
[0m23:14:45.746196 [info ] [MainThread]: Running with dbt=1.7.2
[0m23:14:45.751716 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/usr/app/dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:14:45.764012 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:14:45.778441 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.11983409, "process_user_time": 10.642919, "process_kernel_time": 1.662733, "process_mem_max_rss": "91064", "process_in_blocks": "77496", "process_out_blocks": "611", "command_success": false}
[0m23:14:45.801172 [debug] [MainThread]: Command `dbt run` failed at 23:14:45.800215 after 0.14 seconds
[0m23:14:45.808425 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f977fb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f75fac50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21f75fad40>]}
[0m23:14:45.811401 [debug] [MainThread]: Flushing usage events
